# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pokemon_colours_dict": "00_core.ipynb",
         "load_pokemon_colours": "00_core.ipynb",
         "PokemonColours": "00_core.ipynb",
         "get_colormap": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tcapelle.github.io/pokepalette/"

git_url = "https://github.com/tcapelle/pokepalette/tree/master/"

def custom_doc_links(name): return None
